services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "54321:5432"
    env_file:
      - .env
    volumes:
      - "./db:/var/lib/postgresql/data"
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"